#:schema node_modules/wrangler/config-schema.json
name = "bolt"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./build/client"
send_metrics = false
main = "build/server/index.js"
compatibility_date = "2025-09-15"
node_compat = true
